spring:
  application:
    name: API de agendamentos
  datasource:
    url: jdbc:mysql://localhost:3306/agendamentos?serverTimezone=America/Sao_Paulo
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
